### ISSUE TITLE
Example with ploomber.clients.S3Client

### ISSUE THREAD

**Issue by priamai** [ploomber/projects#24]
Hi there,
I am struggling to understand how can I use the S3Client to download and upload product files into a pipeline.
I am assuming is similar to the SQL example but besides creating the client in clients.py I am not sure how to specify in the tasks to download files.
Any help is welcome!

**Comment by priamai** [comment]
Okay let me try it and will feedback here.

**Comment by priamai** [comment]
Pictures better than words

![image](https://user-images.githubusercontent.com/57333254/154979258-869af338-b5d7-4d98-bea2-5c0a869d8fbd.png)

![image](https://user-images.githubusercontent.com/57333254/154979291-260b012f-a9d6-4d25-a6e7-c80b1764d402.png)

**Comment by priamai** [comment]
Forgot to mention the output:

```
(base) jovyan@1a3714ecaaf2:~/work/ploomber/s3client$ ploomber build
Error: Failed to determine task class for source 'S3Client': Invalid dotted path 'S3Client'. Value must be a dot separated string, with at least two parts: [module_name].[function_name]. 
```

**Comment by edublancas** [comment]
Alright, so your `clients` section just needs one change. However, the tasks section does not need any references to the client, since it's automatically managed by ploomber, here's an example:

```yaml
clients:
    # tell ploomber to use the client returned by clients.get to manage all output files
    File: clients.get

tasks:
  - source: tasks.some_function
    # ploomber will upload this upon execution 
    product: output/get.parquet

  - source: scripts/some-script.py
    # ploomber will upload this upon execution
    product:
        nb: output/nb.html
        model: output/model.pickle

```

If you only want to upload some of the files (and not all), you can pass the client to specific tasks:


```yaml
tasks:
  - source: tasks.some_function
    product: output/get.parquet

  - source: scripts/some-script.py
    product:
        nb: output/nb.html
        model: output/model.pickle
    client: clients.get
```

**Comment by edublancas** [comment]
added example here: https://github.com/ploomber/projects/tree/master/cookbook/file-client

**Comment by priamai** [comment]
What about some examples for downloading data, e.g. I want a step where I pull down objects from the bucket and process them.

**Comment by edublancas** [comment]
Good point. We don't have examples like that yet since initially, the client's purpose was to backup pipeline results for later review. So far, users who want to download files for later processing use the APIs from their services directly. In your case, it'd be calling boto3.

However, we're working on a cloud service for Ploomber (that will allow you to run Ploomber pipelines in the cloud without code changes) so data ingestion is a feature we'll develop soon.

**Comment by priamai** [comment]
Hi there, yes that makes sense now. 
Another question: does the SQL module is read only as well e.g. SELECT only?
With this syntax:

```
clients:
    # tell ploomber to use the client returned by clients.get to manage all output files
    File: clients.get
```

Could I have multiple identifiers for example:


```
clients:
    # tell ploomber to use the client returned by clients.get to manage all output files
    LocalFile: clients.get_file
    AwsFile: clients.get_s3
    GcpFile: clients.get_gcp
```

Do I still have to reference them via the function name syntax or can I use the identifier?


 ```
 - source: scripts/some-script.py
   # this task has a client, upload output files
    product:
        nb: output/nb.html
        model: output/model.pickle
    client: clients.get_gcp


```

Btw the example you provided works fine on my AWS setup.

**Comment by idomichael** [comment]
@priamai can you list here what you're expecting the client to do besides downloads? Is it for reproducibility/experiments tracking?
This will help us better define the reqs for when we build it 😊

**Comment by edublancas** [comment]
The SQL clients can also create tables and views. [See this example.](https://github.com/ploomber/projects/blob/master/templates/spec-api-sql/pipeline.yaml)

It's not possible to have multiple identifiers, because those identifiers correspond to products/task classes in Ploomber ([more in the docs](https://docs.ploomber.io/en/latest/api/spec.html#clients)).

Example:

```yaml
clients:
   # key must be a valid task class or product class

   # File is a product class - this means "upload all files"
   File: clients.s3_client

  # SQLScript is a task class - this means "execute all SQL scripts using this client"
   SQLScript: clients.db_client

   # keys cannot be arbitrary identifiers
   some-identifier: clients.some_client
```

More on [product vs task clients here](https://docs.ploomber.io/en/latest/user-guide/faq_index.html#why-do-products-have-clients).
