### ISSUE TITLE
Static analysis error

### ISSUE THREAD

**Issue by Chutlhu** [ploomber/projects#93]
I have the following pipeline to create hparam space:
```yaml
tasks:
  - source: scripts/2_make_hparams.sh
    product:
      data: products/configs/config-[[config]].yaml
    name: model_hparams-
    static_analysis: disable
    grid:
      - config: 'nn'
      - config: 'sp'
        sp_smoothing: [1e-6, 1e-5, 1e-4]
```
with related shell file:
```bash
config={{config}}

echo "config: $config"

if [ $config == "nn" ]; then
    echo "No params"
    ### DO STUFF
elif [ $config == "sp" ]; then
    sp_smoothing={{sp_smoothing}}
    ### DO STUFF
else
    echo "config not recognized"
    exit 1
fi
```

I am experiencing the following error:
```bash
TypeError: __init__() got an unexpected keyword argument 'static_analysis'
```
Without `static_analysis`, I have error because some parameters are not defined. Am I doing something wrong?
